# run: conda update conda
# run: conda update --all
# run: conda env create --file environment.yml
# run: conda activate tdt4265

name: tdt4265
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - jupyter
  - scikit-learn
  - scipy
  - numpy
  - pathlib
  - pandas
  - requests
  - python-dotenv
  - qgrid
  - seaborn
  - Pillow
  - cython
  - matplotlib
  - scikit-image
  - opencv
  - imgaug
  - IPython[all]
  - pip
  - pytorch
  - torchvision
  - tqdm

